### ISSUE TITLE
GE02: laajenna edistyneiden digitointiominaisuuksien harjoitusta

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/master-training-data#36]
GE02 QGIS kaavoittajille

Harjoitus 2: Edistyneet digitointiominaisuudet voisi olla sisällöltään kurssin GS002 vastaavaa harjoitusta 2 vastaava, sillä GS002-kurssin harjoituksessa käydään näitä erityisesti kaavoittajille tärkeitä toiminnallisuuksia tarkemmin läpi.

**Comment by JuhoErvasti** [comment]
Completed by proxy in 62683cec68d771df5222dcf4da9b9efeb91be96d
