### ISSUE TITLE
GP007: Change all .shp to .gpkg

### ISSUE THREAD

**Issue by jeeemil** [GispoCoding/master-training-data#41]
Same issue as #40  but for course GP007. This should be of higher priority, because this course is to held sooner.

**Comment by jeeemil** [comment]
Issue relevant at least in Exercise 3.

**Comment by jeeemil** [comment]
@eemilhaa I did a rapid update of the course directory. It should be up-to-date now. The course starts tomorrow. Do you have time to go through the .shp -> .gpkg today? No worries if you are busy, then'll do it.

**Comment by jeeemil** [comment]
@eemilhaa According to Meri not super critical to get it done before the start of the course.

**Comment by mmalmari** [comment]
tarkennuksena: muutetaan tekstiin harjoitus aineistot .shp >> .gpkg  Jaettavassa kurssihakemistossa aineistot on jo muutettu. Mutta tämä kurssi tosiaan takana nyt niin ei niin kiireinen.

PS. I don't see the point of discussing this in english :D

**Comment by eemilhaa** [comment]
Closing as this was fixed in https://github.com/GispoCoding/master-training-data/commit/9cdc514d137c6de7eac16e00646e9105bc4046e5
