### ISSUE TITLE
Table font to Karla

### ISSUE THREAD

**Issue by jeeemil** [GispoCoding/master-training-data#42]
Right now it seems that fonts in tables automatically appear in another font than the "Karla" font that's used elsewhere in body text. Perhaps the font in tables should be changed to match the body text.  Hopefully this change could be made by just modifying the .css file.

**Comment by JuhoErvasti** [comment]
I'll close this as I went ahead and accidentally merged [this](https://github.com/GispoCoding/master-training-data/pull/63).
