### ISSUE TITLE
GP002: Exercise 4 drop mention of TieViiva.gpkg 

### ISSUE THREAD

**Issue by jeeemil** [GispoCoding/master-training-data#48]
In GP002 Exercise 4 the TieViiva.gpkg is mentioned to be added, but it is not used anywhere. In order to minimise the size of the data directory I suggest we drop the mention of adding the TieViiva.gpkg layer.

**Comment by jeeemil** [comment]
Anni is updating the data directory accordingly

**Comment by JuhoErvasti** [comment]
Fixed in https://github.com/GispoCoding/master-training-data/commit/6bd3ddef537e28e0d3bb7c711af47ed0ebfe1a83
