### ISSUE TITLE
GP001: Harjoitus 8 kuva 23 on hämäävä

### ISSUE THREAD

**Issue by JuhoErvasti** [GispoCoding/master-training-data#5]
GP001

**Kuvaus**

Kuva 23 liittyen päällekkäisyyden poistamisen työkaluun on hämäävä, kuvassa on todennäköisesti käytetty tracing- työkalua offsetilla, jota ei ole ohjeistettu harjoitusohjeissa ja on siksi harhaanjohtava kyseisessä vaiheessa.

**Lisätietoja**

**Comment by jeeemil** [comment]
@JuhoErvasti Oletko ehtinyt tätä miettiä? Mä voisin muuten tehdä muutokset ennen ensi viikon kurssia. Jos ehdit katselmoida loppuviikolla?
